#!/bin/bash

echo ""
echo "⬡ devstack dev workflow"
echo "========================"
echo ""
echo "DAILY WORKFLOW:"
echo "  ./scripts/feature.sh   — start a new feature branch"
echo "  ./scripts/ship.sh      — run tests, lint, commit, and push"
echo "  ./scripts/done.sh      — clean up after a PR is merged"
echo ""
echo "BRANCH WORKFLOW:"
echo "  1. ./scripts/feature.sh        create a new branch"
echo "  2. write code, run tests"
echo "  3. ./scripts/ship.sh           commit and push"
echo "  4. open PR on GitHub"
echo "  5. review and merge on GitHub"
echo "  6. ./scripts/done.sh           return to main, delete branch"
echo ""
echo "USEFUL GIT COMMANDS:"
echo "  git status                     see what's changed"
echo "  git log --oneline              see recent commits"
echo "  git diff                       see uncommitted changes"
echo "  git stash                      temporarily save changes"
echo "  git stash pop                  restore stashed changes"
echo ""
echo "DOCKER:"
echo "  sudo docker-compose up         start the app"
echo "  sudo docker-compose restart    restart after config changes"
echo "  sudo docker-compose logs       see app logs"
echo ""
echo "TESTING:"
echo "  pytest tests/ -v               run all tests"
echo "  pytest tests/test_posts.py -v  run a specific test file"
echo ""
echo "TIPS:"
echo "  - one feature per branch"
echo "  - ship small and often"
echo "  - always run tests before shipping"
echo "  - PR descriptions help future-you understand why you made changes"
echo ""